export enum PathNames{
    dashboard = 'dashboard',
    catalog = 'catalog',
    productDetails = 'catalog/product/details',
    products = 'products',
    productsList = 'products-list',
    productForm = 'product-form',
    cart = 'cart',
    profile = 'profile',
    pos = 'pos',
    users = 'users',
    userDetails = 'users/details',
    userForm = 'user-form',
    reports = 'reports',
    admin = 'admin',
    settings = 'settings',
    orders = 'orders',
    ordersManagement = 'orders-management'
};